---
#      _                    _         _   _     
#     | | __ _ _ __ ___    / \  _   _| |_| |__  
#  _  | |/ _` | '_ ` _ \  / _ \| | | | __| '_ \ 
# | |_| | (_| | | | | | |/ ___ \ |_| | |_| | | |
#  \___/ \__,_|_| |_| |_/_/   \_\__,_|\__|_| |_|
# @copyright (c) 2016 All rights reserved, JamAuth
# @author    JamAuth
# @website   http://jamauth.com/

#Secret Code used by server to connect to JamAuth API
secretKey: xxxxxx

#Native language of JamAuth [en, de, es, nl]
lang: en
#Number of tries can be used by a player to authenticate, -1 to disable
authAttempts: 3
#Number of seconds for a player to authenticate, -1 to disable
authTimeout: 120
#Enable traditional command authentication method
command: true
#Enable direct authenticatation method
direct: false
#Email is required for registration
email: false

recipe:
 #Password storage purpose, can be changed to [SimpleAuth, ServerAuth]
 type: JamAuth
 #For advanced modification (Don't edit if you don't know what this is)
 data: []

logging:
 #Log all registration events, false to disable
 register: true
 #Log all login events, false to disable
 login: true
 #Log all info message sent to console, false to disable
 info: false
 #Log all info errors occured, false to disable
 error: true
...
